plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.fk.weather'
    compileSdk 35

    defaultConfig {
        applicationId "com.fk.weather"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        viewBinding true    //开启ViewBinding
        buildConfig = true //开启buildConfig
    }

    //加载so文件
    sourceSets{
        main{
            jniLibs.srcDir 'libs'
            jni.srcDirs = []    //disable automatic ndk-build
        }
    }


}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    //依赖子模块
    implementation project(path: ':library')

    //数据解析
    implementation 'com.google.code.gson:gson:2.8.9'
    //图片加载
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    //网络请求
    implementation 'com.lzy.net:okgo:3.0.4'

    //Room数据库
    implementation 'androidx.room:room-runtime:2.4.2'
    annotationProcessor 'androidx.room:room-compiler:2.4.2'
    //Room 支持RxJava2
    implementation 'androidx.room:room-rxjava2:2.4.2'
    //腾讯MMKV
    implementation 'com.tencent:mmkv:1.2.11'
    //Gson
    implementation 'com.google.code.gson:gson:2.9.0'

}